shopnice/utils/forms/LoginForm.py
"""
This file contains class that are used to create LoginForm for the application.
"""

from wtforms import (
    Form,  # Importing the base class for forms
    validators,  # Importing validators for form fields
    StringField,  # Importing the field class for string/text inputs
    PasswordField,  # Importing the field class for password inputs
)


# Import default form style
from .FormInputStyle import inputStyle


# Form class for Login
class LoginForm(Form):
    """
    This class creates a form for logging in.
    """

    # StringField for username with validators for length and input requirement
    userName = StringField(
        "Username",
        [validators.Length(min=4, max=25), validators.InputRequired()],
        render_kw={"class": inputStyle(), "placeholder": "Business Name"},
    )
    # PasswordField for password with validators for length and input requirement
    password = PasswordField(
        "Password",
        [validators.Length(min=5), validators.InputRequired()],
        render_kw={"class": inputStyle(), "placeholder": "password"},
    )

shopnice/utils/forms/SignUpForm.py
"""
This file contains class that are used to create SignUpForm for the application.
"""

# Importing necessary modules from WTForms library
from wtforms import (
    Form,  # Importing the base class for forms
    validators,  # Importing validators for form fields
    EmailField,  # Importing the field class for email inputs
    StringField,  # Importing the field class for string/text inputs
    PasswordField,  # Importing the field class for password inputs
)


# Import default form style
from .FormInputStyle import inputStyle


# Form class for Signing Up
class SignUpForm(Form):
    """
    This class creates a form for signing up.
    """

    # StringField for username with validators for length and input requirement
    userName = StringField(
        "Username",
        [validators.Length(min=4, max=25), validators.InputRequired()],
        render_kw={"class": inputStyle(), "placeholder": "Business Name"},
    )
    # EmailField for email with validators for length and input requirement
    email = EmailField(
        "Email",
        [validators.Length(min=6, max=50), validators.InputRequired()],
        render_kw={"class": inputStyle(), "placeholder": "email"},
    )
    # PasswordField for password with validators for length and input requirement
    password = PasswordField(
        "Password",
        [
            validators.Length(min=8),
            validators.InputRequired(),
        ],
        render_kw={"class": inputStyle(), "placeholder": "password"},
    )
    # PasswordField for confirming password with validators for length and input requirement
    passwordConfirm = PasswordField(
        "passwordConfirm",
        [
            validators.Length(min=8),
            validators.InputRequired(),
        ],
        render_kw={"class": inputStyle(), "placeholder": "confirm your password"},
    )

shopnice/routes/signup.py
# Import necessary modules and functions
from modules import (
    Log,  # Logging module
    ssl,  # SSL/TLS module
    abort,  # Function for aborting requests
    flash,  # Flash messaging module
    session,  # Session management module
    sqlite3,  # SQLite database module
    request,  # Module for handling HTTP requests
    smtplib,  # SMTP client module
    redirect,  # Function for redirecting requests
    APP_NAME,  # Constant for application name
    SMTP_PORT,  # SMTP port number
    SMTP_MAIL,  # SMTP email address
    RECAPTCHA,  # Recaptcha module
    addPoints,  # Function for adding points to user
    Blueprint,  # Blueprint class for creating modular applications
    encryption,  # Encryption module
    SignUpForm,  # Form for user sign-up
    SMTP_SERVER,  # SMTP server address
    EmailMessage,  # Class for creating email messages
    requestsPost,  # Module for making HTTP POST requests
    REGISTRATION,  # Flag for enabling/disabling user registration
    SMTP_PASSWORD,  # SMTP password
    DB_USERS_ROOT,  # Path to the users database
    render_template,  # Function for rendering templates
    currentTimeStamp,  # Function for getting current timestamp
    RECAPTCHA_SIGN_UP,  # Flag for enabling/disabling Recaptcha for sign-up
    RECAPTCHA_SITE_KEY,  # Recaptcha site key
    RECAPTCHA_VERIFY_URL,  # Recaptcha verification URL
    RECAPTCHA_SECRET_KEY,  # Recaptcha secret key
)

# Create a blueprint for the signup route
signUpBlueprint = Blueprint("signup", __name__)


# Define the route handler for the signup page
@signUpBlueprint.route("/signup", methods=["GET", "POST"])
def signup():
    """
    This function handles the sign up route.

    If the user is already signed in, they will be redirected to the homepage.
    If the user submits the sign up form, their information is checked to ensure it is valid.
    If the information is valid, their account is created and they are signed in.

    Returns:
    The sign up page with any errors or a confirmation message.
    """
    # Check if registration is enabled
    match REGISTRATION:
        # If registration is enabled
        case True:
            # Check if the user is already logged in
            match "userName" in session:
                # If user is already logged in, redirect to homepage
                case True:
                    Log.danger(f'USER: "{session["userName"]}" ALREADY LOGGED IN')
                    return redirect("/")
                # If user is not logged in
                case False:
                    # Create sign up form object
                    form = SignUpForm(request.form)
                    # Check if request method is POST (form submitted)
                    match request.method == "POST":
                        # If form is submitted
                        case True:
                            # Extract form data
                            userName = request.form["userName"]
                            email = request.form["email"]
                            password = request.form["password"]
                            passwordConfirm = request.form["passwordConfirm"]
                            # Remove spaces from username
                            userName = userName.replace(" ", "")
                            Log.sql(
                                f"Connecting to '{DB_USERS_ROOT}' database"
                            )  # Log the database connection is started
                            # Connect to the database
                            connection = sqlite3.connect(DB_USERS_ROOT)
                            connection.set_trace_callback(
                                Log.sql
                            )  # Set the trace callback for the connection
                            cursor = connection.cursor()
                            # Fetch existing usernames and emails from the database
                            cursor.execute("select userName from users")
                            users = str(cursor.fetchall())
                            cursor.execute("select email from users")
                            mails = str(cursor.fetchall())
                            # Check if username and email are available
                            match not userName in users and not email in mails:
                                # If username and email are available
                                case True:
                                    # Check if passwords match
                                    match passwordConfirm == password:
                                        # If passwords match
                                        case True:
                                            # Check if username contains only ASCII characters
                                            match userName.isascii():
                                                # If username contains only ASCII characters
                                                case True:
                                                    # Hash the password
                                                    password = encryption.hash(password)
                                                    # Connect to the database
                                                    connection = sqlite3.connect(
                                                        DB_USERS_ROOT
                                                    )
                                                    connection.set_trace_callback(
                                                        Log.sql
                                                    )  # Set the trace callback for the connection
                                                    # Check if reCAPTCHA is enabled for sign up
                                                    match RECAPTCHA and RECAPTCHA_SIGN_UP:
                                                        # If reCAPTCHA is enabled
                                                        case True:
                                                            # Verify reCAPTCHA response
                                                            secretResponse = request.form[
                                                                "g-recaptcha-response"
                                                            ]
                                                            verifyResponse = requestsPost(
                                                                url=f"{RECAPTCHA_VERIFY_URL}?secret={RECAPTCHA_SECRET_KEY}&response={secretResponse}"
                                                            ).json()
                                                            # If reCAPTCHA verification is successful
                                                            match verifyResponse[
                                                                "success"
                                                            ] == True or verifyResponse[
                                                                "score"
                                                            ] > 0.5:
                                                                # If reCAPTCHA verification is successful
                                                                case True:
                                                                    Log.success(
                                                                        f"Sign up reCAPTCHA | verification: {verifyResponse['success']} | verification score: {verifyResponse['score']}",
                                                                    )
                                                                    # Insert user data into the database
                                                                    cursor = (
                                                                        connection.cursor()
                                                                    )
                                                                    cursor.execute(
                                                                        f"""
                                                                        insert into users(userName,email,password,profilePicture,role,points,timeStamp,isVerified) \
                                                                        values(?, ?, ?, ?, ?, ?, ?, ?)
                                                                        """,
                                                                        (
                                                                            userName,
                                                                            email,
                                                                            password,
                                                                            f"https://api.dicebear.com/7.x/identicon/svg?seed={userName}&radius=10",
                                                                            "user",
                                                                            0,
                                                                            currentTimeStamp(),
                                                                            "False",
                                                                        ),
                                                                    )
                                                                    connection.commit()
                                                                    # Log user addition
                                                                    Log.success(
                                                                        f'User: "{userName}" added to database',
                                                                    )

shopnice/templates/tailwindUI/changePassword.html.jinja
{% extends 'layout.html.jinja' %}
{% block head %}
<!-- Set the title of the page to "Change Password" -->
<title>Change Password</title>
<!-- End of the head block -->
{% endblock head %}
{% block body %}
<!-- Start of the body block -->
<div class="text-center mt-32">
  {% if recaptcha %}
  <!-- Check if recaptcha is enabled -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>
  <!-- Create a form with recaptcha -->
  <form method="post" class="mx-auto w-fit mt-8" id="recaptchaForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Render form fields for old password, new password, and password confirmation -->
    {{ form.oldPassword() }} {{ form.password() }} {{ form.passwordConfirm() }}
    <!-- Add the recaptcha button for changing the password -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Change My Password
    </button>
  </form>
  {% else %}
  <!-- If recaptcha is not enabled, create a form without it -->
  <form method="post" class="mx-auto w-fit mt-8">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Render form fields for old password, new password, and password confirmation -->
    {{ form.oldPassword() }} {{ form.password() }} {{ form.passwordConfirm() }}
    <!-- Add a button for changing the password -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Change My Password
    </button>
  </form>
  {% endif %}
</div>
<!-- End of the body block -->
{% endblock body %}

shopnice/templates/tailwindUI/changeProfilePicture.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title of the page to "Change Profile Picture" -->
<title>Change Profile Picture</title>
{% endblock head %}

{% block body %}
<div class="text-center mt-32">
  <div class="mb-3">
    <!-- Display the default profile picture seed URL -->
    <p>https://api.dicebear.com/7.x/identicon/svg?seed={SEED}</p>
    <!-- Provide information about the default seed (username) and a link for more information -->
    <small>default seed is your username</small><br />
    <a href="https://www.dicebear.com/styles/identicon/" target="_blank">
      <small>click for more information about profile picture seeds</small>
    </a>
  </div>
  <div>
    {% if recaptcha %}
    <!-- Include Google reCAPTCHA scripts if recaptcha is enabled -->
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>
    <!-- Form for changing profile picture seed with reCAPTCHA -->
    <form method="post" id="recaptchaForm">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <!-- Include the form field for entering a new profile picture seed -->
      {{ form.newProfilePictureSeed() }}
      <!-- Submit button with reCAPTCHA integration -->
      <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
        class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
        set seed
      </button>
    </form>
    {% else %}
    <!-- Form for changing profile picture seed without reCAPTCHA -->
    <form method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <!-- Include the form field for entering a new profile picture seed -->
      {{ form.newProfilePictureSeed() }}
      <!-- Submit button without reCAPTCHA -->
      <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
        set seed
      </button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock body %}

shopnice/templates/tailwindUI/csrfError.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Head block is intentionally left empty for this template -->
{% endblock head %}

{% block body %}
<div class="w-fit mx-auto text-center mt-16 text-lg">
  <!-- Display a message indicating the user should fill the form again -->
  <h1>Fill the same form again.</h1>
  <!-- Display the reason for filling the form again (supplied by the 'reason' variable) -->
  <p>Reason: {{ reason }}</p>
</div>
{% endblock body %}

shopnice/templates/tailwindUI/editPost.html.jinja
{% extends 'layout.html.jinja' %}
{% block head %}
<!-- Set the title of the Edit Post page -->
<title>Edit Post</title>
{% endblock head %}

{% block body %}
<!-- Container for the Edit Post content -->
<div class="w-fit mx-auto mt-8">

  {% if recaptcha %}
  <!-- Include scripts for Google reCAPTCHA -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>

  <!-- Form for editing post with reCAPTCHA -->
  <form method="post" id="recaptchaForm" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Input fields for post title and tags -->
    {{ form.postTitle(autocomplete="off") }} {{ form.postTags(autocomplete="off") }}
    <p class="text-xs text-center w-fit mx-auto mb-2">(separate with comma)</p>

    <!-- Section for current and new post banners -->
    <div class="w-fit mx-auto text-center my-4">
      <p class="mb-2">Current Banner</p>
      <img src="{{ url_for('returnPostBanner.returnPostBanner', postID = id) }}"
        class="h-48 group-hover:scale-110 transition duration-150 object-cover w-max rounded-t-md mx-auto select-none" />
      <p class="mt-2">New Banner</p>
      {{ form.postBanner(class_="") }}
    </div>

    <!-- Select a Category dropdown -->
    <div class="mx-auto w-fit">
      <label class="block my-1 text-center">Select a Category</label>
      {{ form.postCategory() }}
    </div>

    <!-- Post content editor -->
    <div>
      {{ form.postContent(id_="editor", autocomplete="off") }}
    </div>

    <!-- Save button with reCAPTCHA integration -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium">
      Save
    </button>
  </form>

  {% else %}

  <!-- Form for editing post without reCAPTCHA -->
  <form method="post" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Input fields for post title and tags -->
    {{ form.postTitle(autocomplete="off") }} {{ form.postTags(autocomplete="off") }}
    <p class="text-xs text-center w-fit mx-auto mb-2">(separate with comma)</p>

    <!-- Section for current and new post banners -->
    <div class="w-fit mx-auto text-center my-4">
      <p class="mb-2">Current Banner</p>
      <img src="{{ url_for('returnPostBanner.returnPostBanner', postID = id) }}"
        class="h-48 group-hover:scale-110 transition duration-150 object-cover w-max rounded-t-md mx-auto select-none" />
      <p class="mt-2">New Banner</p>
      {{ form.postBanner(class_="") }}
    </div>

    <!-- Select a Category dropdown -->
    <div class="mx-auto w-fit">
      <label class="block my-1 text-center">Select a Category</label>
      {{ form.postCategory() }}
    </div>

    <!-- Post content editor -->
    <div>
      {{ form.postContent(id_="editor", autocomplete="off") }}
    </div>

    <!-- Save button without reCAPTCHA -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium">
      Save
    </button>
  </form>
  {% endif %}
</div>
{% endblock body %}

shopnice/templates/tailwindUI/layout.html.jinja
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Meta tags for character set, compatibility, viewport, and theme color -->
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="theme-color" content="#171717" />
  <!-- Square form starts -->

   <!-- Karakter encoding -->
    <meta charset="utf-8">
    <!-- 
        Perintah agar lebar viewport mengikuti lebar perangkat
        dan skala mengikuti ukuran ketika web di-load
     -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Shop nice</title>
    <!-- Load bootstrap stylesheet -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <!-- Load login stylesheet -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">

  <!-- Square form ends -->
  <!-- Favicon link -->
  <link rel="icon" href="{{ url_for('static', filename='img/shop_nice.png') }}">

  <!-- External stylesheet link for Tailwind CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/general.css') }}" />
  <script src="https://cdn.tailwindcss.com"></script>

  <!-- External stylesheet link for Tabler Icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.46.0/tabler-icons.min.css" />

  <!-- Custom block for additional head content -->



     <!-- ========== All CSS files linkup for ========= -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="assets/css/lineicons.css" />
    <link rel="stylesheet" href="assets/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="assets/css/fullcalendar.css" />
    <link rel="stylesheet" href="assets/css/main.css" />
 
  {% block head %} {% endblock head %}
</head>

<body id="body">
  <!-- Include changeTheme component -->
  {% from "components/changeTheme.html.jinja" import changeTheme %}
  {{ changeTheme() }}

  <!-- Include navbar component -->
  {% include 'components/navbar.html.jinja'%}

  <!-- Include flash messages component -->
  {% from "components/flash.html.jinja" import flash %}
  {{ flash() }}

  <!-- Custom block for additional body content -->
  {% block body %} {% endblock body %}

  <!-- External scripts and styles for jQuery, Summernote editor, timestamp, and optional reCAPTCHA badge -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
  <script src="{{ url_for('static', filename='js/editor.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/editor.css') }}" />
  <script src="{{ url_for('static', filename='js/timeStamp.js') }}"></script>
  {% if not recaptchaBadge %}
  <!-- Optional stylesheet for reCAPTCHA badge -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/recaptcha.css') }}" />
  {% endif %}
</body>

</html>

shopnice/templates/tailwindUI/login.html
{% extends 'layout.html.jinja'%}
{%block head%}
<!-- Set the title of the page to "Login" -->
<title>Login</title>
<!-- End of the head block -->
{% endblock head %}
{%block body%}
<!-- Start of the body block -->
  <div>
  <div class="container-fluid">
        <div class="card card-login">
            <div class="card-body">
                <div class="row justify-content-center">
                    <div class="col-lg-6 col-md-12">
                        <div class="padding bg-primary text-center align-items-center d-flex">
                            <div id="particles-js"></div>
                            <div class="w-100">
                                <div class="logo mb-4">
                                    <img src="{{ url_for('static', filename='img/iconCookie.png') }}" alt="kodinger logo" class="img-fluid">
                                </div>
                                <h4 class="text-light mb-2">Shop nice</h4>
                                <p class="lead text-light">Powered by Square, Google Gemini AI and Stable diffusion</p>
                                <button class="btn btn-block btn-icon btn-icon-google mb-3">
                                        <a
                                     href='/square'>
                                    Login With Square
                                </a>
                                </button>
                            </div>

                            <div class="help-links">
                                <ul>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12">
                        <div class="padding">
                            <h2>Signup</h2>
                            <p class="lead">Before you get started, you must login or register if you don't already have an account.</p>

  {% if recaptcha %}
  <!-- Check if recaptcha is enabled -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>
  <!-- Create a form with recaptcha -->
  <form method="post" id="recaptchaForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Render form fields for username and password with autocomplete turned off -->
    {{form.userName(autocomplete="off")}}{{form.password(autocomplete="off")}}
    <!-- Add the recaptcha button for login -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Login
    </button>
    <!-- Add a link for password reset -->
    <a href="/passwordreset/codesent=false" id="passwordReset"
      class="hover:text-rose-500 duration-150 text-sm font-normal select-none">Forgot password?</a>
  </form>
  {% else %}
  <!-- If recaptcha is not enabled, create a form without it -->
   <form method="post">
     <!-- Autofill username and password -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="hidden" name="userName" value="{{ access_token }}" />
    <input type="hidden" name="password" value="{{ merchant_id }}" />
    <!-- Add a button for login -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
        Login
    </button>
    <!-- Add a link for password reset -->
    <a href="/passwordreset/codesent=false" id="passwordReset"
        class="hover:text-rose-500 duration-150 text-sm font-normal select-none">Forgot password?</a>
</form>
  {% endif %}



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




</div>
<!-- End of the body block -->
{% endblock body %}


    <script src="{{ url_for('static', filename='js/particles.js') }}"></script>
    <script>
        particlesJS.load('particles-js', '{{ url_for('static', filename='particlesjs-config.json') }}', function() {
          console.log('callback - particles.js config loaded');
        });
    </script>

shopnice/templates/tailwindUI/searchBar.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title of the page to "Search" -->
<title>Search</title>
{% endblock head %}

{% block body %}
<div class="w-fit mx-auto mt-32">
  <!-- Search bar input and button -->
  <div>
    <input type="text" id="searchBarInput" autocomplete="off" placeholder="search"
      class="w-72 h-10 text-xl m-2 rounded-md p-2 text-center outline-rose-500 bg-transparent focus:outline-none focus:ring focus:ring-rose-500 duration-150" />
    <button onclick="searchBar()" class="hover:text-rose-500 duration-150">
      <i class="ti ti-search ml-2 text-2xl"></i>
    </button>
  </div>
</div>

<!-- Include the JavaScript file for search functionality -->
<script src="{{ url_for('static', filename='js/searchBar.js') }}"></script>
{% endblock body %}

shopnice/templates/tailwindUI/signup.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title of the page to "Signup" -->
<title>Signup</title>
{% endblock head %}

{% block body %}
<div class="w-fit mx-auto mt-24 md:mt-44 text-center text-xl">
  {% if recaptcha %}
  <!-- Include reCAPTCHA scripts if recaptcha is enabled -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>

  <!-- Signup form with reCAPTCHA -->
  <form method="post" id="recaptchaForm" action="{{ url_for('signup.signup') }}">
    <!-- CSRF token for form security -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Form fields for username, email, password, and password confirmation -->
    {{form.userName(autocomplete="off")}}
    {{form.email(autocomplete="off")}}
    {{form.password()}}
    {{form.passwordConfirm()}}

    <!-- Signup button with reCAPTCHA integration -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Signup
    </button>
  </form>
  {% else %}
  <!-- Signup form without reCAPTCHA -->
  <form method="post">
    <!-- CSRF token for form security -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Form fields for username, email, password, and password confirmation -->
    {{form.userName(autocomplete="off")}}
    {{form.email(autocomplete="off")}}
    {{form.password()}}
    {{form.passwordConfirm()}}

    <!-- Signup button without reCAPTCHA integration -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Signup
    </button>
  </form>
  {% endif %}

  <!-- App Privacy Policy warning text -->
  <div class="text-xs select-none">By signing up, you accept <a href="/privacyPolicy"
      class="font-medium text-rose-500 hover:text-rose-600 duration-150">Privacy Policy</a></div>
</div>
{% endblock body %}